version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: mongod --bind_ip_all
    ports: 
      - 27017:27017
    networks: 
      mynet:
        ipv4_address: 172.18.0.4   


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      mynet:
        ipv4_address: 172.18.0.5

  scrapy:
    build:
      context: . 
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - mongo
      - mongo-express
    networks: 
      mynet:
        ipv4_address: 172.18.0.6
  
networks:
  mynet:
    ipam: 
      driver: default
      config:
        - subnet: "172.18.0.0/16"
        
     
    